### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by kansi** [codedge-llc/pigeon#101]
#### Description

I tried to execute the following example listed in the docs 
```elixir
    n = Pigeon.FCM.Notification.new(dev_ids, %{}, msg)
    Pigeon.FCM.push(n)
```

they give the following error

```
16:16:09.631 [error] GenServer #PID<0.231.0> terminating
** (MatchError) no match of right hand side value: {:error, {{:callback_mode, :ok}, {:child, :undefined, #Reference<0.0.2.1345>, {Kadabra.Stream, :start_link, [%Kadabra.Stream{body: "", buffer: "", connection: #PID<0.231.0>, flow: %Kadabra.Stream.FlowControl{max_frame_size: 16384, queue: [], stream_id: 1, window: 1048576}, headers: [], id: 1, ref: #Reference<0.0.2.1299>, scheme: :https, settings: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.7128>, :tls_connection, :undefined}, #PID<0.233.0>}, uri: 'fcm.googleapis.com'}]}, :transient, 5000, :worker, [Kadabra.Stream]}}}
    (kadabra) lib/connection/flow_control.ex:146: Kadabra.Connection.FlowControl.process/2
    (kadabra) lib/connection.ex:225: Kadabra.Connection.do_send_headers/3
    (kadabra) lib/connection.ex:107: Kadabra.Connection.handle_cast/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:send, :headers, [{":method", "POST"}, {":path", "/fcm/send"}, {"authorization", "key=SERVER_KEY"}, {"content-type", "application/json"}, {"accept", "application/json"}], "{\"to\":\"DEVICE_ID\",\"priority\":\"normal\",\"data\":{\"body\":\"test message \"}}"}}
State: %Kadabra.Connection{buffer: "", client: #PID<0.230.0>, flow_control: %Kadabra.Connection.FlowControl{active_stream_count: 0, active_streams: #MapSet<[]>, queue: [], settings: %Kadabra.Connection.Settings{enable_push: true, header_table_size: 4096, initial_window_size: 1048576, max_concurrent_streams: 100, max_frame_size: 16384, max_header_list_size: 16384}, stream_id: 1, window: 1048576}, opts: [scheme: :https, ssl: [{:active, :once}, {:packet, :raw}, {:reuseaddr, true}, {:alpn_advertised_protocols, ["h2"]}, :binary], port: 443, reconnect: false], reconnect: false, ref: #Reference<0.0.2.1299>, scheme: :https, socket: {:sslsocket, {:gen_tcp, #Port<0.7128>, :tls_connection, :undefined}, #PID<0.233.0>}, uri: 'fcm.googleapis.com'}
```

Any clues on what might be causing the isssue.

#### Environment details
Elixir: 1.4.5
pigeon: "1.1.1"
kadabra: "0.3.4"

**Comment by hpopp** [comment]
What are your elixir, erlang, pigeon, and kadabra versions?

**Comment by kansi** [comment]
@hpopp Updated the issue description.

**Comment by hpopp** [comment]
Erlang version too, pigeon isn't supported on OTP versions earlier than 19.2

**Comment by kansi** [comment]
@hpopp That might be the cause, I am running `Erlang/OTP 19`.

**Comment by kansi** [comment]
@hpopp Upgrading to `Erlang/OTP 19.2` fixed the issue 👍 . It would be great if the `README` specfies the same.

**Comment by hpopp** [comment]
Will do. I wish hex could enforce OTP versions.

**Comment by kansi** [comment]
We all do !
