### ISSUE TITLE
FCM Poison parsing errors

### ISSUE THREAD

**Issue by asgoel** [codedge-llc/pigeon#83]
just deployed an app using the new FCM workers to production and I'm seeing the following errors come through quite a bit. looks like the response isn't valid json according to Poison...

```
** (Poison.SyntaxError) Unexpected token at position 143: {
    (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (pigeon) lib/pigeon/fcm/worker.ex:193: Pigeon.FCM.Worker.process_end_stream/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:end_stream, %Kadabra.Stream.Response{body: "{\"multicast_id\":5100906380876488637,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1501697155598441%2e36f6e02e36f6e0\"}]}{\"multicast_id\":5670313992973191076,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1501697155958054%2e36f6e02e36f6e0\"}]}", headers: [{":status", "200"}, {"content-type", "application/json; charset=UTF-8"}, {"date", "Wed, 02 Aug 2017 18:05:55 GMT"}, {"expires", "Wed, 02 Aug 2017 18:05:55 GMT"}, {"cache-control", "private, max-age=0"}, {"x-content-type-options", "nosniff"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"server", "GSE"}, {"alt-svc", "quic=\":443\"; ma=2592000; v=\"39,38,37,36,35\""}, {"accept-ranges", "none"}, {"vary", "Accept-Encoding"}, {":status", "200"}, {"content-type", "application/json; charset=UTF-8"}, {"date", "Wed, 02 Aug 2017 18:05:55 GMT"}, {"expires", "Wed, 02 Aug 2017 18:05:55 GMT"}, {"cache-control", "private, max-age=0"}, {"x-content-type-options", "nosniff"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"server", "GSE"}, {"alt-svc", "quic=\":443\"; ma=2592000; v=\"39,38,37,36,35\""}, {"accept-ranges", "none"}, {"vary", "Accept-Encoding"}], id: 1, status: 200}}
```

**Comment by asgoel** [comment]
Here is the body, separated out, looks like it's actually not valid JSON.
```
 "{\"multicast_id\":5100906380876488637,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1501697155598441%2e36f6e02e36f6e0\"}]}{\"multicast_id\":5670313992973191076,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1501697155958054%2e36f6e02e36f6e0\"}]}"
```

**Comment by hpopp** [comment]
That looks like two JSON responses chunked into the same stream response with one cleaved off. I bet its probably related to #84

**Comment by asgoel** [comment]
Yeah, that's why I was confused... could be related to #84 but could also be just bad JSON from FCM. The obvious hack is to add square brackets around the entire thing if Poison can't parse it, and try again, but that seems a little sketchy

**Comment by hpopp** [comment]
Has this, #84, or #85 cropped up recently?
